# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
  - stage: Deploy
    displayName: 'Deploy to Azure'
    jobs:
      - job: CopyFiles
        displayName: 'Deploy Python Script'
        pool:
          name: Default
          agent.name: TLV-M-MarkD
        steps:
          - task: CopyFilesOverSSH@0
            inputs:
              sshEndpoint: 'az2vm'
              sourceFolder: '$(Build.SourcesDirectory)/pyblob'
              contents: '**'
              targetFolder: '/home/userazure1/pyblob/'
              cleanTargetFolder: true
              cleanHiddenFilesInTarget: true
              readyTimeout: '20000'
              failOnEmptySource: true

          - task: SSH@0
            inputs:
              sshEndpoint: 'az2vm'
              runOptions: 'inline'
              inline: |
                python -m venv antenv
                source antenv/bin/activate
                python -m pip install --upgrade pip
                pip install setup
                pip install --target="./.python_packages/lib/site-packages" -r ./requirements.txt