# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- vm_creations

resources:
  containers:
    - container: azure-cli
      image: mcr.microsoft.com/azure-cli

stages:
- stage: ProvisionVM
  displayName: 'Provision VM'
  jobs:
  - job: ProvisionVMJob
    displayName: 'Provision VM Job'
    pool:
      name: Default
      agent.name: TLV-M-MarkD
    steps:
    - task: AzureCLI@2
      displayName: 'Create Azure VM'
      inputs:
        azureSubscription: 'azure1-conn'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Create a unique name for the VM
          VM_NAME="my-vm-$(date +%s)"

          # Set resource group and VM details
          RESOURCE_GROUP="hw-rg"
          LOCATION=$(az group show --name $RESOURCE_GROUP --query location --output tsv)
          IMAGE="Canonical:0001-com-ubuntu-server-focal:20_04-lts-gen2:latest"
          SIZE="Standard_B1s"
          USERNAME="azureuser1"
          PASSWORD="azurpassword1!"

          # Create VM
          az vm create \
            --name $VM_NAME \
            --resource-group $RESOURCE_GROUP \
            --location $LOCATION \
            --image $IMAGE \
            --size $SIZE \
            --admin-username $USERNAME \
            --admin-password $PASSWORD