# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- sa_creations

stages:
  - stage: Deploy
    displayName: 'Deploy to Azure'
    jobs:
      - job: ProvisionSA
        displayName: 'Provision Storage Account'
        pool:
          name: Default
          agent.name: TLV-M-MarkD

        steps:
          - task: AzureCLI@2
            displayName: 'Check Resource Group Existence'
            inputs:
              azureSubscription: 'azure1-conn'
              scriptType: 'bash'
              scriptLocation: 'inline'
              inlineScript: |
                rgExists=$(az group exists --name hw-rg)
                echo "Resource Group exists: $rgExists"

          - task: AzureCLI@2
            displayName: 'Create Resource Group'
            condition: eq(variables['rgExists'], 'False')
            inputs:
              azureSubscription: 'azure1-conn'
              scriptType: 'bash'
              scriptLocation: 'inline'
              inlineScript: |
                az group create --name hw-rg --location eastus

          - task: AzureCLI@2
            displayName: 'Provision Storage Account'
            inputs:
              azureSubscription: 'azure1-conn'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az deployment group create --resource-group hw-rg --template-file 'ARMTemplates/SA.json' --parameters 'ARMTemplates/SA.parameters.json'
