# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

# pool:
#   name: Default
#   agent.name: TLV-M-MarkD

resources:
  containers:
    - container: azure-cli
      image: mcr.microsoft.com/azure-cli

stages:
- stage: ProvisionStorageAccount
  displayName: 'Provision Storage Account'
  jobs:
  - job: ProvisionStorageAccountJob
    displayName: 'Provision Storage Account Job'
    pool:
      name: Default
      agent.name: TLV-M-MarkD
    steps:
    - task: AzureCLI@2
      displayName: 'Install Azure CLI'
      inputs:
        azureSubscription: '<Azure Service Connection>'
        scriptLocation: 'inlineScript'
        inlineScript: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az --version
    - task: AzureCLI@2
      displayName: 'Create Azure Storage Account'
      inputs:
        azureSubscription: 'azure1-conn'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Create a unique name for the storage account
          STORAGE_ACCOUNT_NAME="sa$(date +%s | md5sum | head -c 8)"

          # Set resource group and storage account details
          RESOURCE_GROUP="hw-rg"
          LOCATION=$(az group show --name $RESOURCE_GROUP --query location --output tsv)
          
          # Create storage account
          az storage account create \
            --name $STORAGE_ACCOUNT_NAME \
            --resource-group $RESOURCE_GROUP \
            --location $LOCATION \
            --sku Standard_LRS
