# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default
  agent.name: TLV-M-MarkD

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'azure1-conn'
    subscriptionId: '904c28cc-7663-4aeb-94e7-e1b1156533d8'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'hw-rg'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/subandshadow/arm/main/create_web_app/StorageAccount.json'
    overrideParameters: '-storageAccountName $(Build.BuildId)'
    deploymentMode: 'Incremental'
    deploymentName: 'CreateSAWithARMTemplate'
