# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- vm_creations


stages:
  - stage: Deploy
    displayName: 'Deploy to Azure'
    jobs:
      - job: ProvisionVM
        displayName: 'Provision VM'
        pool:
          name: Default
          agent.name: TLV-M-MarkD

        steps:
          - task: AzureCLI@2
            displayName: 'Provision VM'
            inputs:
              azureSubscription: 'azure1-conn' # Replace with your Azure service connection name
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az deployment group create --resource-group hw-rg --template-file 'ARMTemplates/VM.json' --parameters 'ARMTemplates/VM.parameters.json'
